### ISSUE TITLE
Decide how to proceed to next question

### ISSUE THREAD

**Issue by Jhappy77** [Jhappy77/cpsc559-project-front-end#29]
How will we go from one question to another?
We may need a special "next question" button for the host. If we do it this way, the backend will also probably need to send socket notifications to all the players, and the players will need to respond.

One placeholder approach might be to have everything on a timer (ex: the question results only shows for so long, then the next question is fetched). This is not necessarily ideal but will probably be relatively easily to implement given our time constraints.

Whoever assigns themselves this issue should decide on an approach and make additional issues as necessary.

**Comment by Jhappy77** [comment]
Once we get the polling done for initialization, I will make a recommendation on how to proceed with this (while getting everyone's input) and then we can assemble everything as necessary.

**Comment by desileal** [comment]
Next question button used to go from question to question
